- project:
    merge-mode: squash-merge
    templates:
      - publish-to-pypi
      - publish-otc-docs-pti
      - release-notes-jobs
    check:
      jobs:
        - otc-tox-pep8
    gate:
      jobs:
        - otc-tox-pep8
