- job:
    name: otcdocstheme-tox-pep8
    parent: otc-tox-pep8
    description: |
      Run pep8 check

- job:
    name: otcdocstheme-tox-buildpdf
    parent: otc-tox
    description: |
      Run buildpdf target
    vars:
      tox_envlist: pdf-docs

- job:
    name: otcdocstheme-tox-html
    parent: otc-tox
    description: |
      Run html target
    vars:
      tox_envlist: html

- project:
    merge-mode: squash-merge
    templates:
      - publish-to-pypi
    check:
      jobs:
        - otc-tox-pep8
        - otcdocstheme-tox-buildpdf
        - otcdocstheme-tox-html
    gate:
      jobs:
        - otc-tox-pep8
        - otcdocstheme-tox-buildpdf
        - otcdocstheme-tox-html
