- project:
    merge-mode: squash-merge
    default-branch: main
    vars:
      sphinx_install_package: true
    templates:
      - publish-to-pypi
      - publish-otc-docs-hc-pti
      - release-notes-jobs
    check:
      jobs:
        - otc-tox-pep8
        - build-otc-api-ref
    gate:
      jobs:
        - otc-tox-pep8
