- job:
    name: otcdocstheme-tox-pep8
    parent: otc-tox-pep8
    description: |
      Run pep8 check

- job:
    name: otcdocstheme-tox-html
    parent: otc-tox
    description: |
      Run html target
    vars:
      tox_envlist: html

- job:
    name: otcdocstheme-apiref-src
    parent: build-otc-api-ref
    description: |
      Run tox -e api-ref with src otc-api-ref
    required-projects:
      - opentelekomcloud/otcdocstheme
      - opentelekomcloud-infra/otc-api-ref

- project:
    merge-mode: squash-merge
    templates:
      - publish-to-pypi
      - publish-otc-docs-pti
      - release-notes-jobs
    check:
      jobs:
        - otc-tox-pep8
        - otcdocstheme-apiref-src
        - build-otc-api-ref
    gate:
      jobs:
        - otc-tox-pep8
        - otcdocstheme-tox-html
